export interface BookingTypes {
    session_id: string,
    uuid: string,
    date: string,
    time: string,
    luggage: string,
    passenger: string,
    selected_location: string,
    children: string,
    pickup_address: string,
    dropoff_address: string,
    from_airport: string,
    to_airport: string,
    vehicle_name: string,
    distance: string,
    night_charge: string,
    total_fare: string,
    luggage_charge: string,
    extra_toll: string,
    airport_toll: string,
}